// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createTodo, getTodos, type Options, updateTodo } from '../sdk.gen';
import type { CreateTodoData, CreateTodoResponse, GetTodosData, GetTodosResponse, UpdateTodoData, UpdateTodoResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getTodosQueryKey = (options?: Options<GetTodosData>) => createQueryKey('getTodos', options);

/**
 * List todos
 */
export const getTodosOptions = (options?: Options<GetTodosData>) => queryOptions<GetTodosResponse, DefaultError, GetTodosResponse, ReturnType<typeof getTodosQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTodos({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTodosQueryKey(options)
});

/**
 * Create a todo
 */
export const createTodoMutation = (options?: Partial<Options<CreateTodoData>>): UseMutationOptions<CreateTodoResponse, DefaultError, Options<CreateTodoData>> => {
    const mutationOptions: UseMutationOptions<CreateTodoResponse, DefaultError, Options<CreateTodoData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createTodo({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update a todo
 */
export const updateTodoMutation = (options?: Partial<Options<UpdateTodoData>>): UseMutationOptions<UpdateTodoResponse, DefaultError, Options<UpdateTodoData>> => {
    const mutationOptions: UseMutationOptions<UpdateTodoResponse, DefaultError, Options<UpdateTodoData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateTodo({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
