// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

export type Todo = {
    id: number;
    title: string;
    done: boolean;
    createdAt: string;
};

export type CreateTodo = {
    title: string;
};

export type UpdateTodo = {
    title?: string;
    done?: boolean;
};

export type GetTodosData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/todos';
};

export type GetTodosResponses = {
    /**
     * OK
     */
    200: Array<Todo>;
};

export type GetTodosResponse = GetTodosResponses[keyof GetTodosResponses];

export type CreateTodoData = {
    body: CreateTodo;
    path?: never;
    query?: never;
    url: '/todos';
};

export type CreateTodoResponses = {
    /**
     * Created
     */
    201: Todo;
};

export type CreateTodoResponse = CreateTodoResponses[keyof CreateTodoResponses];

export type UpdateTodoData = {
    body: UpdateTodo;
    path: {
        id: number;
    };
    query?: never;
    url: '/todos/{id}';
};

export type UpdateTodoResponses = {
    /**
     * OK
     */
    200: Todo;
};

export type UpdateTodoResponse = UpdateTodoResponses[keyof UpdateTodoResponses];
