// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zTodo = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    title: z.string().min(1).max(120),
    done: z.boolean(),
    createdAt: z.iso.datetime()
});

export const zCreateTodo = z.object({
    title: z.string().min(1).max(120)
});

export const zUpdateTodo = z.object({
    title: z.string().min(1).max(120).optional(),
    done: z.boolean().optional()
});

/**
 * OK
 */
export const zGetTodosResponse = z.array(zTodo);

export const zCreateTodoBody = zCreateTodo;

/**
 * Created
 */
export const zCreateTodoResponse = zTodo;

export const zUpdateTodoBody = zUpdateTodo;

export const zUpdateTodoPath = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

/**
 * OK
 */
export const zUpdateTodoResponse = zTodo;
